services:
  directus:
    image: directus/directus:11.3.2
    restart: unless-stopped
    user: root
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_AUTO_PURGE: ${CACHE_AUTO_PURGE}
      CACHE_STORE: ${CACHE_STORE}
      REDIS: ${REDIS}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/snapshots:/directus/snapshots
      - ./directus/migrations:/directus/migrations
    ports:
      - "8055:8055"
    depends_on:
      - cache
      - database

  database:
    image: postgis/postgis:13-3.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" # open port for remote connection with ssh tunnel

  cache:
    image: redis:6.2.10-alpine
    restart: unless-stopped

  unsplash-proxy:
    build:
      context: ./services/unsplash-proxy
    restart: unless-stopped
    ports:
      # open port for host network
      - "127.0.0.1:8080:8080"
